### PR TITLE
Support asynchronously loading geometry and images (#14)

### PR DESCRIPTION
**Pull request by bluemarvin**
Will make creating gl textures and vertex arrays off main render thread a follow up issue. Will create a branch of FxR that uses new API.

### CODE REVIEW

**Comment by bluemarvin** [comment]
@MortimerGoro Actually hold off on this PR, I found a few things I need to update while integrating with FxR

**Comment by bluemarvin** [comment]
Okay, I think it is ready for review.

**Comment by bluemarvin** [comment]
FxR WIP branch: https://github.com/MozillaReality/FirefoxReality/tree/async

I still need to do SVR and Oculus. Will be traveling tomorrow so might not get a chance for a day or two.

**Comment by MortimerGoro** [comment]
Code looks good and it runs ok.

Just one thing. I was checking how the data is passed to TextureGLPtr, and I think that we are leaking the data of the texture in memory (std::unique_ptr<uint8_t[]>& aImage). It's assigned to MipMap.data but not cleared after the GL texture is created.

**Comment by bluemarvin** [comment]
> Just one thing. I was checking how the data is passed to TextureGLPtr, and I think that we are leaking the data of the texture in memory (std::unique_ptr<uint8_t[]>& aImage). It's assigned to MipMap.data but not cleared after the GL texture is created.

The image data is retained so that we can recreate the GL texture when the gl context gets recreated. It gets deleted when the TextureGL gets deleted.

**Comment by MortimerGoro** [comment]
> The image data is retained so that we can recreate the GL texture when the gl context gets recreated. It gets deleted when the TextureGL gets deleted.

Ok, as an optimization we could try to store the path and reload from file when possible (A 2048 image  takes 16MB vs just a string with the path)

We can do that as a follow up.

**Pull request merged**
